trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'anandjoy7/myreactapp'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- task: DockerInstaller@0
  displayName: 'Install Docker'

- checkout: self

- script: |
    docker build -t $(imageName):$(Build.BuildId) .
    docker tag $(imageName):$(Build.BuildId) $(imageName):latest
  displayName: 'Build Docker image'

- task: Docker@2
  displayName: 'Login to Docker Hub'
  inputs:
    command: 'login'
    containerRegistry: 'DockerHub7'  # Ensure DockerHub7 matches your Docker service connection name

- task: Docker@2
  displayName: 'Push Docker image'
  inputs:
    command: 'push'
    repository: $(imageName)
    tags: |
      $(Build.BuildId)
      latest
